server:
  port: ${icutool.server.port}
  servlet:
    context-path: /backend
spring:
  datasource:
    url: jdbc:mysql://${icutool.mysql.ip}:${icutool.mysql.port}/${icutool.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${icutool.mysql.username}
    password: ${icutool.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  kafka:
    bootstrap-servers: ${kafka-url}
    producer:
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: icutool-push
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  redis:
    # Redis服务器地址
    host: ${icutool.redis.host}
    # Redis服务器端口号
    port: ${icutool.redis.port}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
  #    password: ${icutool.redis.password}
  jackson:
    time-zone: GMT+8
  flyway:
    # 启用或禁用 flyway
    enabled: true
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。这个默认值是 false 理论上作为默认配置是不科学的。
    clean-disabled: true
    # SQL 脚本的目录,多个路径使用逗号分隔 默认值 classpath:db/migration
    locations: classpath:db
    #  metadata 版本控制信息表 默认 flyway_schema_history
    table: flyway_schema_history
    # 如果没有 flyway_schema_history 这个 metadata 表， 在执行 flyway migrate 命令之前, 必须先执行 flyway baseline 命令
    # 设置为 true 后 flyway 将在需要 baseline 的时候, 自动执行一次 baseline。
    baseline-on-migrate: true
    # 指定 baseline 的版本号,默认值为 1, 低于该版本号的 SQL 文件, migrate 时会被忽略
    baseline-version: 1
    # 字符编码 默认 UTF-8
    encoding: UTF-8
    # 是否允许不按顺序迁移 开发建议 true  生产建议 false
    out-of-order: false
    # 需要 flyway 管控的 schema list,这里我们配置为flyway  缺省的话, 使用spring.datasource.url 配置的那个 schema,
    # 可以指定多个schema, 但仅会在第一个schema下建立 metadata 表, 也仅在第一个schema应用migration sql 脚本.
    # 但flyway Clean 命令会依次在这些schema下都执行一遍. 所以 确保生产 spring.flyway.clean-disabled 为 true
    schemas: icutool
    # 执行迁移时是否自动调用验证   当你的 版本不符合逻辑 比如 你先执行了 DML 而没有 对应的DDL 会抛出异常
    validate-on-migrate: true
  security:
    loginType: json
#logging:
#  level:
#    org.springframework.web: debug
#    springfox: warn
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: cn.icutool.domain
jwt:
  secret: ${icutool.jwt.secret}
knife4j:
  enable: true
  openapi:
    title: icutool
    description: 一个集成多个程序的小工具
    # aaa"
    email: no1plus88@gmail.com
    concat: PB
    url: https://icutool.cn
    version: v1.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
wx:
  mp:
    #    callback: http://f4cd-113-92-129-127.ngrok.io
    callback: ${icutool.wx.callback}
    expireTime: ${icutool.wx.expireTime}
    configs:
      - appId: ${icutool.wx.appId} # 第一个公众号的appid
        secret: ${icutool.wx.secret} # 公众号的appSecret
        token: ${icutool.wx.token} # 接口配置里的Token值
        aesKey: ${icutool.wx.aesKey} # 接口配置里的EncodingAESKey值
    autoResp: ${icutool.wx.autoResp}
#======================================minio======================================
minio:
  access-key: ${icutool.minio.ak}
  secret-key: ${icutool.minio.sk}
  url: ${icutool.minio.url}
  open-url: ${icutool.minio.open-url}
  bucket-name: ${icutool.minio.bucket-name}
  expired: ${icutool.minio.expired}
